import type { Metadata } from "next";
import { GeistSans } from "geist/font/sans";
import "./globals.css";
import { ThemeProvider } from "@/components/providers/theme-provider";
import { ProgressBar } from "@/components/ui/progress-bar";
import { Toaster } from "sonner";
import { Suspense } from "react";

export const metadata: Metadata = {
	title: "Create Next App",
	description: "Generated by create next app",
};

export default function RootLayout({
	children,
}: {
	children: React.ReactNode;
}) {
	return (
		<html lang="en">
			<body className={`${GeistSans.className} relative`}>
				<ThemeProvider attribute="class" defaultTheme="light">
					<Suspense fallback={null}>
						<ProgressBar />
					</Suspense>{" "}
					<Toaster />
					{children}
				</ThemeProvider>
			</body>
		</html>
	);
}
