import type { Metadata } from 'next';
import { Inter } from 'next/font/google';
import './globals.css';
import { ThemeProvider } from '@/components/providers/theme-provider';
import { ProgressBar } from '@/components/ui/progress-bar';
import { Toaster } from 'sonner';

const inter = Inter({ subsets: ['latin'] });

export const metadata: Metadata = {
  title: 'Create Next App',
  description: 'Generated by create next app'
};

export default function RootLayout({
  children
}: {
  children: React.ReactNode;
}) {
  return (
    <html lang='en'>
      <body className={inter.className + ' relative'}>
        <ThemeProvider attribute='class' defaultTheme='light'>
          <ProgressBar />
          <Toaster />
          {children}
        </ThemeProvider>
      </body>
    </html>
  );
}
